#!/bin/sh
#
# nginx - this script starts and stops the nginx daemin
#
# chkconfig:   - 85 15
# description: Nginx is an HTTP(S) server, HTTP(S) reverse proxy and IMAP/POP3 proxy server
# processname: nginx
# config:      /opt/server/web/nginx/conf/nginx.conf
# pidfile:     /opt/server/web/nginx/var/run/nginx.pid

# Source function library.
. /etc/rc.d/init.d/functions

# Source networking configuration.
. /etc/sysconfig/network

# Check that networking is up.
[ "$NETWORKING" = "no" ] && exit 0

CMD=/opt/server/web/nginx/sbin/nginx
PID=/opt/server/web/nginx/var/run/nginx.pid

CONF_FILE=/opt/server/web/nginx/conf/nginx.conf
LOCK_FILE=/opt/server/web/nginx/var/lock/nginx

if [ -f $CONF_FILE ];then 	
fi

prog=$(basename $CMD)

start() {
    [ -x $CMD ] || exit 5
    [ -f $CONF_FILE ] || exit 6
    echo -n $"Starting $prog: "
    daemon --pidfile $PID $CMD -c $CONF_FILE
    retval=$?
    echo
    [ $retval -eq 0 ] && touch $LOCK_FILE
    return $retval
}

stop() {
    echo -n $"Stopping $prog: "
    killproc -p $PID $prog
    retval=$?
    echo
    [ $retval -eq 0 ] && rm -f $PID $LOCK_FILE
    return $retval
}

restart() {
    stop
    start
}

reload() {
    echo -n $"Reloading $prog: "
    killproc $CMD -HUP
    retval=$?
    echo
}

force_reload() {
    restart
}

rh_status() {
    status -p $PID $prog
}

rh_status_q() {
    rh_status >/dev/null 2>&1
}

case "$1" in
    start)
        rh_status_q && exit 0
        $1
        ;;
    stop)
        rh_status_q || exit 0
        $1
        ;;
    restart|configtest)
        $1
        ;;
    reload)
        rh_status_q || exit 7
        $1
        ;;
    force-reload)
        force_reload
        ;;
    status)
        rh_status
        ;;
    condrestart|try-restart)
        rh_status_q || exit 0
;;
    *)
        echo $"Usage: $0 {start|stop|status|restart|condrestart|try-restart|reload|force-reload}"
        exit 2
esac